CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    description VARCHAR(255),
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(255),
    brand VARCHAR(255),
    category VARCHAR(255),
    date_added TIMESTAMP,
    expiry_date TIMESTAMP,
    last_updated TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    product_image VARCHAR(255),
    purchase_price NUMERIC(10,2),
    quantity INTEGER NOT NULL,
    selling_price NUMERIC(10,2) NOT NULL,
    sku_code VARCHAR(255) UNIQUE,
    status VARCHAR(255),
    supplier VARCHAR(255),
    supplier_email VARCHAR(255),
    unit_type VARCHAR(255),
    warehouse_location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL,
    total_items INTEGER,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255),
    company VARCHAR(255),
    created_at TIMESTAMP,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    supplier_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

-- High-performance database indexes for search, sorting, and pagination
CREATE INDEX IF NOT EXISTS idx_items_name ON inventory_items(name);
CREATE INDEX IF NOT EXISTS idx_items_category ON inventory_items(category);
CREATE INDEX IF NOT EXISTS idx_items_status ON inventory_items(status);

